CREATE TABLE users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username varchar(30) NOT NULL UNIQUE CHECK (username ~ '^[A-Za-z0-9_]{3,30}$'),
 email varchar(254) NOT NULL,
 password_hash varchar(255) NOT NULL,
 bio varchar(500) NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_lower_idx ON users(lower(email));
CREATE UNIQUE INDEX users_username_lower_idx ON users(lower(username));
CREATE TABLE manga (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 slug varchar(160) NOT NULL UNIQUE,
 title varchar(200) NOT NULL,
 alternate_title varchar(200),
 author varchar(200) NOT NULL,
 description text NOT NULL,
 status varchar(20) NOT NULL CHECK (status IN ('ONGOING','COMPLETED','HIATUS')),
 genres varchar(300) NOT NULL,
 official_url varchar(500),
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE chapters (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 manga_id bigint NOT NULL REFERENCES manga(id) ON DELETE CASCADE,
 number numeric(8,2) NOT NULL CHECK(number > 0),
 title varchar(200),
 released_at timestamptz NOT NULL,
 official_url varchar(500),
 UNIQUE(manga_id, number)
);
CREATE INDEX chapters_release_idx ON chapters(released_at DESC, id DESC);
CREATE INDEX manga_status_idx ON manga(status);
CREATE TABLE user_manga_progress (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 manga_id bigint NOT NULL REFERENCES manga(id) ON DELETE CASCADE,
 current_chapter numeric(8,2) NOT NULL DEFAULT 0 CHECK(current_chapter >= 0),
 reading_status varchar(20) NOT NULL DEFAULT 'READING' CHECK(reading_status IN ('READING','COMPLETED','ON_HOLD','DROPPED')),
 updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(user_id,manga_id)
);
CREATE TABLE manga_follows (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 manga_id bigint NOT NULL REFERENCES manga(id) ON DELETE CASCADE,
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(user_id,manga_id)
);
CREATE INDEX manga_follows_manga_idx ON manga_follows(manga_id);
CREATE INDEX progress_manga_idx ON user_manga_progress(manga_id);
