ALTER TABLE chapters ALTER COLUMN released_at DROP NOT NULL;
ALTER TABLE chapters DROP CONSTRAINT chapters_number_check;
ALTER TABLE chapters ADD CONSTRAINT chapters_number_check CHECK (number >= 0);
ALTER TABLE chapters ADD COLUMN description text;
ALTER TABLE chapters ADD COLUMN official_link_kind varchar(20) NOT NULL DEFAULT 'SERIES';
ALTER TABLE chapters ADD COLUMN source varchar(40);
ALTER TABLE chapters ADD COLUMN indexed_at timestamptz NOT NULL DEFAULT now();
CREATE TABLE chapter_sync (
 manga_id bigint PRIMARY KEY REFERENCES manga(id) ON DELETE CASCADE,
 provider_id uuid,
 checked_at timestamptz,
 status varchar(20) NOT NULL DEFAULT 'PENDING'
);
CREATE TABLE discussion_posts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 chapter_id bigint NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
 user_id bigint REFERENCES users(id) ON DELETE SET NULL,
 parent_id bigint REFERENCES discussion_posts(id),
 body varchar(5000) NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 5000),
 created_at timestamptz NOT NULL DEFAULT now(),
 deleted_at timestamptz
);
CREATE INDEX discussion_chapter_idx ON discussion_posts(chapter_id, created_at, id);
CREATE TABLE request_limits (
 key_hash varchar(64) PRIMARY KEY,
 attempts integer NOT NULL,
 resets_at timestamptz NOT NULL
);
CREATE INDEX request_limits_expiry_idx ON request_limits(resets_at);
