import { readFile, writeFile, rename } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { setTimeout as delay } from "node:timers/promises";

const root = new URL("../", import.meta.url);
const fields = `id status title { english romaji native } synonyms popularity siteUrl
  coverImage { large } genres staff(perPage:10) { edges { role node { name { full } } } }`;
const query = `query ($page:Int!, $excluded:[Int]) { Page(page:$page,perPage:50) {
  pageInfo { hasNextPage }
  media(type:MANGA,format:MANGA,countryOfOrigin:"JP",status:RELEASING,isAdult:false,sort:ID,id_not_in:$excluded) { ${fields} }
} }`;

// Stable ID ordering and exclusion batches avoid the 5,000-entry offset limit.
export async function fetchOngoing(request, onProgress = () => {}) {
  const entries = new Map();
  let pageNumber = 1;
  let excluded = [];
  for (;;) {
    const { Page: page } = await request(query, { page: pageNumber, excluded });
    if (
      !Array.isArray(page?.media) ||
      typeof page.pageInfo?.hasNextPage !== "boolean"
    )
      throw new Error("Invalid catalog page");
    if (page.pageInfo.hasNextPage && !page.media.length)
      throw new Error("Empty intermediate page");
    for (const entry of page.media) {
      if (
        !Number.isSafeInteger(entry.id) ||
        entries.has(entry.id) ||
        entry.status !== "RELEASING"
      )
        throw new Error("Invalid catalog cursor or release status");
      entries.set(entry.id, entry);
    }
    onProgress(entries.size);
    if (!page.pageInfo.hasNextPage) break;
    pageNumber++;
    if (pageNumber > 100) {
      excluded = [...entries.keys()];
      if (excluded.length > 10000)
        throw new Error(
          "Provider exclusion limit exceeded; partition the import before refreshing",
        );
      pageNumber = 1;
    }
  }
  return entries;
}

export function normalize(entry, existing) {
  const title = (
    existing?.title ??
    entry.title.english ??
    entry.title.romaji ??
    entry.title.native
  )?.slice(0, 200);
  if (!title || !Number.isSafeInteger(entry.popularity) || entry.popularity < 0)
    throw new Error(`Invalid metadata for ${entry.id}`);
  const status = {
    RELEASING: "ONGOING",
    FINISHED: "COMPLETED",
    CANCELLED: "COMPLETED",
    HIATUS: "HIATUS",
  }[entry.status];
  if (!status) throw new Error(`Unsupported status ${entry.status}`);
  const slug =
    existing?.slug ??
    `${
      (entry.title.romaji ?? title)
        .normalize("NFKD")
        .replace(/[\u0300-\u036f]/g, "")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")
        .slice(0, 140) || "manga"
    }-${entry.id}`;
  const author =
    existing?.author ??
    ([
      ...new Set(
        entry.staff.edges
          .filter((edge) => /story|art|original creator/i.test(edge.role))
          .map((edge) => edge.node.name.full),
      ),
    ]
      .join(" / ")
      .slice(0, 200) ||
      "Author not listed");
  const genres = entry.genres.join(", ").slice(0, 300);
  return {
    id: existing?.id ?? 1000000 + entry.id,
    slug,
    title,
    alternateTitle:
      [
        ...new Set(
          [
            entry.title.romaji,
            entry.title.native,
            ...(entry.synonyms ?? []),
          ].filter((t) => t && t !== title),
        ),
      ]
        .join(" · ")
        .slice(0, 200) || null,
    author,
    description:
      existing?.description ??
      `${title} is a manga${genres ? ` in ${genres.toLowerCase()}` : ""}.`,
    status,
    genres,
    officialUrl: existing?.officialUrl ?? null,
    sourceId: entry.id,
    sourceUrl: `https://anilist.co/manga/${entry.id}`,
    coverUrl:
      /^https:\/\/s4\.anilist\.co\/file\/anilistcdn\/media\/manga\//.test(
        entry.coverImage?.large ?? "",
      )
        ? entry.coverImage.large
        : null,
    popularity: entry.popularity,
  };
}

export function catalogSql(catalog) {
  const columns = [
    "slug",
    "title",
    "alternate_title",
    "author",
    "description",
    "status",
    "genres",
    "official_url",
    "source_id",
    "source_url",
    "cover_url",
    "popularity",
  ];
  const keys = [
    "slug",
    "title",
    "alternateTitle",
    "author",
    "description",
    "status",
    "genres",
    "officialUrl",
    "sourceId",
    "sourceUrl",
    "coverUrl",
    "popularity",
  ];
  const literal = (value) =>
    value == null
      ? "NULL"
      : typeof value === "number"
        ? String(value)
        : `'${value.replaceAll("'", "''")}'`;
  return `-- Generated by npm run catalog:sync. Existing IDs and chapter/follow relationships are preserved.\nINSERT INTO manga (${columns.join(", ")}) VALUES\n${catalog.map((entry) => `(${keys.map((key) => literal(entry[key])).join(", ")})`).join(",\n")}\nON CONFLICT (slug) DO UPDATE SET\n${columns
    .slice(1)
    .map((column) => `${column} = EXCLUDED.${column}`)
    .join(",\n")};\n`;
}

async function request(query, variables) {
  for (let attempt = 0; attempt < 5; attempt++) {
    // Below even AniList's degraded 30 requests/minute limit.
    await delay(2200);
    try {
      const response = await fetch("https://graphql.anilist.co", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query, variables }),
        signal: AbortSignal.timeout(30000),
      });
      if (response.status === 429 || response.status >= 500) {
        await delay(
          Math.max(
            2 ** attempt * 3000,
            Number(response.headers.get("retry-after") || 0) * 1000,
          ),
        );
        continue;
      }
      if (!response.ok)
        throw new Error(
          `AniList HTTP ${response.status}: ${await response.text()}`,
        );
      const payload = await response.json();
      if (payload.errors || !payload.data)
        throw new Error(JSON.stringify(payload.errors));
      return payload.data;
    } catch (error) {
      if (attempt === 4) throw error;
      await delay(2 ** attempt * 3000);
    }
  }
  throw new Error("AniList remained unavailable; previous catalog preserved");
}

async function main() {
  const path = new URL("frontend/data/catalog.json", root);
  const previous = JSON.parse(await readFile(path, "utf8"));
  const seedIds = {
    "blue-period": 107237,
    "chainsaw-man": 105778,
    dandadan: 132029,
    "death-note": 30021,
    "fullmetal-alchemist": 30025,
    naruto: 30011,
    "one-piece": 30013,
    "witch-hat-atelier": 98263,
  };
  const existing = new Map(
    previous.map((entry) => [entry.sourceId ?? seedIds[entry.slug], entry]),
  );
  if (existing.has(undefined))
    throw new Error("Existing title needs a source ID mapping");
  const entries = await fetchOngoing(request, (count) => {
    if (count % 250 === 0) console.log(`Fetched ${count} ongoing series`);
  });
  if (
    entries.size < 100 ||
    entries.size <
      previous.filter((entry) => entry.status === "ONGOING").length * 0.8
  )
    throw new Error(
      "Unexpectedly small catalog; preserving the previous snapshot",
    );
  const ongoingCount = entries.size;
  // Refresh titles that ended or went on hiatus; never delete series with discussions.
  const missing = [...existing.keys()].filter((id) => !entries.has(id));
  for (let offset = 0; offset < missing.length; offset += 50) {
    const ids = missing.slice(offset, offset + 50);
    const { Page } = await request(
      `query ($ids:[Int]) { Page(perPage:50) { media(id_in:$ids,type:MANGA) { ${fields} } } }`,
      { ids },
    );
    if (Page.media.length !== ids.length)
      throw new Error(
        "Unable to refresh existing series; previous snapshot preserved",
      );
    for (const entry of Page.media) entries.set(entry.id, entry);
  }
  const catalog = [...entries.values()]
    .map((entry) => normalize(entry, existing.get(entry.id)))
    .sort(
      (a, b) => b.popularity - a.popularity || a.slug.localeCompare(b.slug),
    );
  if (new Set(catalog.map((entry) => entry.slug)).size !== catalog.length)
    throw new Error("Duplicate slug");
  const metadata = {
    provider: "AniList",
    syncedAt: new Date().toISOString(),
    ongoingCount,
    totalItems: catalog.length,
    scope:
      "All non-adult Japanese manga marked RELEASING by AniList; previously imported series retained.",
  };
  const outputs = [
    [path, JSON.stringify(catalog, null, 2) + "\n"],
    [
      new URL("frontend/data/catalog-sync.json", root),
      JSON.stringify(metadata, null, 2) + "\n",
    ],
    [
      new URL(
        "backend/src/main/resources/db/migration/R__synced_catalog.sql",
        root,
      ),
      catalogSql(catalog),
    ],
  ];
  // Fetch and validate the entire run before replacing any last-known-good data.
  for (const [file, contents] of outputs)
    await writeFile(new URL(file.href + ".tmp"), contents);
  for (const [file] of outputs) await rename(new URL(file.href + ".tmp"), file);
  console.log(`Saved ${catalog.length} series (${ongoingCount} ongoing).`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
